runtime: go112
automatic_scaling:
  min_idle_instances: 1 # resident instance
  max_instances: 1 # cap
  min_pending_latency: 10ms # serve ASAP
  max_pending_latency: 10ms # serve ASAP

inbound_services:
- warmup

handlers:
- url: /.*
  script: auto
